version: '3.3'

services:

  app:
    build: './node-app/.'
    ports:
      - "8080:8080"

  api:
    build: './node-api/.'
    ports:
      - "8000:8000"

  proxy:
    build: './proxy/.'
    ports:
      - "80:80"
